
## default connection pool

## PostgreSQL

#drop n create table again, good for testing, comment this in production

#spring.output.ansi.enabled=ALWAYS

#keycloak.security-constraints[0].authRoles[0]=user
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=/customers/*

keycloak:
  auth-server-url: http://localhost:8180/auth
  principal-attribute: preferred_username
  public-client: true
  realm: SpringBootKeycloak
  resource: login-app
server:
  port: 8081
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: 1234
    url: jdbc:postgresql://localhost:5432/springboot_keycloak
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

